fix(ci): Retry version fetching on failure
- Fail if curl encounters request errors or fetched data is null.
- Use `apt-get` instead of `apt` to install deps.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -38,26 +38,35 @@ jobs:
 
       - name: Fetch version info of NekoBox
         id: fetch_version
-        run: |
-          sudo apt install curl jq perl-base
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          command: |
+            sudo apt-get install curl jq perl-base
 
-          base_version=$(curl -s https://pypi.org/pypi/nekobox/json | jq -r ".info.version")
+            base_version=$(curl -sf https://pypi.org/pypi/nekobox/json | jq -r ".info.version")
 
-          if [[ "${{ matrix.tag_variant }}" == "unstable" ]]; then
-            commit_sha=$(curl -s https://api.github.com/repos/wyapx/nekobox/commits/main | jq -r ".sha")
-            tag_name="${base_version}-${commit_sha:0:7}"
-            base_version="${commit_sha}"
-          else
-            tag_name="${base_version}"
-          fi
+            if [[ "${{ matrix.tag_variant }}" == "unstable" ]]; then
+              commit_sha=$(curl -sf https://api.github.com/repos/wyapx/nekobox/commits/main | jq -r ".sha")
+              tag_name="${base_version}-${commit_sha:0:7}"
+              base_version="${commit_sha}"
+            else
+              tag_name="${base_version}"
+            fi
 
-          rev_parsed=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" | perl -pe '$_ = /.*-(rev\.[0-9]+)/ ? $1 : ""')
-          if [[ ! -z "${rev_parsed}" ]]; then
-            tag_name="${tag_name}-${rev_parsed}"
-          fi
+            rev_parsed=$(curl -sf "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" | perl -pe '$_ = /.*-(rev\.[0-9]+)/ ? $1 : ""')
+            if [[ ! -z "${rev_parsed}" ]]; then
+              tag_name="${tag_name}-${rev_parsed}"
+            fi
 
-          echo "base_version=${base_version}" >> $GITHUB_OUTPUT
-          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT
+            if [[ "${base_version}" == "null" ]] || [[ "${tag_name}" == "null" ]]; then
+              echo "Error: null detected"
+              exit 1
+            else
+              echo "base_version=${base_version}" >>$GITHUB_OUTPUT
+              echo "tag_name=${tag_name}" >>$GITHUB_OUTPUT
+            fi
 
       - name: Check if image tag exists
         id: check_image_tag
